id = "oso"
name = "Oso"
version = "0.0.1"
schema_version = 1
authors = ["Oso Security, Inc."]
description = "Support for Oso policies written in Polar."
repository = "https://github.com/osohq/oso-zed"

[grammars.polar]
repository = "https://github.com/osohq/tree-sitter-polar"
rev = "b44da606fd7e095f2a17bfea49085635f2a6c3fb"

[language_servers.polar]
name = "Polar"
languages = ["Polar"]
